---

- name: Ensuring Shibboleth service is running and enabled at system start.
  service:
    name: "{{ hm_shibboleth__daemon_name }}"
    state: started
    enabled: yes

- name: Configuring Shibboleth
  template:
    src: "{{ item }}"
    dest: /etc/shibboleth/shibboleth2.xml
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.shibboleth/shibboleth2.xml.{{ ansible_distribution_release }}.j2"
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.shibboleth/shibboleth2.xml.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.shibboleth/shibboleth2.xml.{{ ansible_distribution_release }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.shibboleth/shibboleth2.xml.j2"
    - "inventory/group_files/servers/honzamach.shibboleth/shibboleth2.xml.{{ ansible_distribution_release }}.j2"
    - "inventory/group_files/servers/honzamach.shibboleth/shibboleth2.xml.j2"
    - "shibboleth2.xml.{{ ansible_distribution_release }}.j2"
    - "shibboleth2.xml.j2"
  notify: Restart shibboleth service

- name: Configuring Shibboleth contact template file
  template:
    src: "{{ item }}"
    dest: /etc/shibboleth/shibboleth_contact_template.xml
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.shibboleth/shibboleth_contact_template.xml.{{ ansible_distribution_release }}.j2"
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.shibboleth/shibboleth_contact_template.xml.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.shibboleth/shibboleth_contact_template.xml.{{ ansible_distribution_release }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.shibboleth/shibboleth_contact_template.xml.j2"
    - "inventory/group_files/servers/honzamach.shibboleth/shibboleth_contact_template.xml.{{ ansible_distribution_release }}.j2"
    - "inventory/group_files/servers/honzamach.shibboleth/shibboleth_contact_template.xml.j2"
    - "shibboleth_contact_template.xml.{{ ansible_distribution_release }}.j2"
    - "shibboleth_contact_template.xml.j2"
  notify: Restart shibboleth service

- name: Configuring Shibboleth attribute map file
  template:
    src: "{{ item }}"
    dest: /etc/shibboleth/attribute-map.xml
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_first_found:
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.shibboleth/attribute-map.xml.{{ ansible_distribution_release }}.j2"
    - "inventory/host_files/{{ inventory_hostname }}/honzamach.shibboleth/attribute-map.xml.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.shibboleth/attribute-map.xml.{{ ansible_distribution_release }}.j2"
    - "inventory/group_files/servers_{{ msms_server_type }}/honzamach.shibboleth/attribute-map.xml.j2"
    - "inventory/group_files/servers/honzamach.shibboleth/attribute-map.xml.{{ ansible_distribution_release }}.j2"
    - "inventory/group_files/servers/honzamach.shibboleth/attribute-map.xml.j2"
    - "attribute-map.xml.{{ ansible_distribution_release }}.j2"
    - "attribute-map.xml.j2"
  notify: Restart shibboleth service

- name: Managing local directory for service metadata
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ playbook_dir }}/spool"
    - "{{ playbook_dir }}/spool/{{ role_name }}"
  delegate_to: localhost
  when: hm_shibboleth__download_metadata

- name: Fetching current service metadata
  get_url:
    url: "https://{{ ansible_fqdn }}/Shibboleth.sso/Metadata"
    dest: "{{ playbook_dir }}/spool/{{ role_name }}/{{ ansible_fqdn }}.metadata.xml"
    mode: 0644
  delegate_to: localhost
  when: hm_shibboleth__download_metadata
