---

- name: Including distribution specific variables
  include_vars: "{{ansible_distribution|lower}}.yml"
  tags:
    - always

#-------------------------------------------------------------------------------

- block:

    - import_tasks: install.debian.yml
      tags:
        - install

    - import_tasks: configure.debian.yml
      tags:
        - configure

  when: ansible_os_family == 'Debian'
